[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "streamify"
version = "0.1.0"
description = "A lightweight frontend for Streamlink and MPV"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Topic :: Multimedia :: Video :: Display",
]

dependencies = [
    "PyQt6",
    "requests",
    "streamlink",
    "python-mpv"
]

[project.gui-scripts]
streamify = "streamify.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["streamify*"]

[tool.setuptools.package-data]
"streamify.ui" = ["styles/*.css"]

[tool.setuptools.data-files]
"share/applications" = ["share/applications/streamify.desktop"]
"share/icons/hicolor/256x256/apps" = ["share/icons/hicolor/256x256/apps/streamify.png"]

[tool.pyright]
venvPath = "."
venv = ".venv"
